" Copyright (c) 2012 Christopher Raymond Abbey
" Free for all to copy, use and share.

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'tmhedberg/matchit'
Plugin 'wincent/command-t'
Plugin 'fatih/vim-go'
Plugin 'kchmck/vim-coffee-script'
Plugin 'elixir-lang/vim-elixir'
Plugin 'leafgarland/typescript-vim'

"
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" change the mapleader from \ to ,
let mapleader=","

"maps edit vimrc to ev
nmap <silent> <leader>ev :e $MYVIMRC<CR>
"maps reload vimrc to sv
nmap <silent> <leader>sv :so $MYVIMRC<CR>

nmap <silent> <leader>nt :NERDTree<CR>

set history=1000 "remember more commands and search history
set undolevels=1000  "use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title  "change terminal's title
set visualbell   "don't beep
set noerrorbells "don't beep

"Prevent vim from writing backup files
set nobackup
set noswapfile

"Allows buffers to be hidden instead of force written or closed
set hidden

" Basic settings
set nowrap        "dont't wrap lines
set backspace=indent,eol,start  "allows backspacing over everything in insert

set autoindent "always set autoindenting on
set number "always show line numbers
set showmatch "always show matching parenthesis
set ignorecase "ignore case while searching
set smartcase  "ignore case if search pattern is all lower casem
               "  case-sensitive otherwise
               
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab  "insert tabs on the start of a line according to shiftwidth, 
              "  not tab stop

set hlsearch "highlight search terms
set incsearch "show search matches as you type

" This shows what you are typing as a command. Especially useful for seeing
" the leader key.
set showcmd

" Clears the search highlighting
nmap <silent> <leader>/ :nohlsearch<CR> 

" Making NERDTree window smaller
let g:NERDTreeWinSize=35

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Used for when i forget to sudo
cmap w!! w !sudo tee % >/dev/null

" Adds a dollar sign to replace and change commands
set cpoptions+=$

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
    if exists("t:NERDTreeBufName")
        if bufwinnr(t:NERDTreeBufName) != -1
            if winnr("$") == 1
                q
            endif
        endif
    endif
endfunction

if has("autocmd")
    autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()
endif

" Toggle NERDTree mapping
nmap <silent> <leader>nt :NERDTreeToggle<CR>

set pastetoggle=<leader>p

" Turning on modelines
set modeline
set modelines=3

syntax on
